services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-server
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./shared:/shared
    working_dir: /shared
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped
    networks:
      - app-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit-app
    ports:
      - "8081:8081"
    volumes:
      - ./shared:/shared
    working_dir: /shared
    command: streamlit run /shared/streamlit.py --server.port=8081
    networks:
      - app-network

  misp:
    extends:
      file: misp-docker/docker-compose.yml
      service: misp-core
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - redis
      - misp-modules
    networks:
      - app-network

  db:
    extends:
      file: misp-docker/docker-compose.yml
      service: db
    networks:
      - app-network

  redis:
    extends:
      file: misp-docker/docker-compose.yml
      service: redis
    networks:
      - app-network

  misp-modules:
    extends:
      file: misp-docker/docker-compose.yml
      service: misp-modules
    networks:
      - app-network

volumes:
  jenkins_home:
  mysql_data:

networks:
  app-network:
    driver: bridge